# this notebook is just for testing and some preprocessing part its not necessary for email generation

In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('ffinal_Emarketing.csv')
df1

,customer_id,product,Recommended_products,customer_name,customer_email,date,last_purchased_month
0,11.0,HQD AIR 5% 1X5PK DISPOSABLE (4000) (Frozen Cho...,"FUME NICKY JAM 10PK (10000) (Summer Amante) , ...",Angelo Difatta,angelo@nepawholesale.com,2024-02-19,2
1,14.0,"WISE TRASH BAG 10CT/26GALLON BLACK , NUTRAMENT...",".LOTY COCONUT WATER 24-500ML , LOTY JUICE 24-5...",Nepa Wholesale,nepawholesale@hotmail.com,2024-05-06,5
2,46.0,FUME 10PK EXTRA 5% DISPOSABLE (1500) (Clear),"VIPER 5PK SUPER 5% (Mint Ice) , ORION BAR 5% 1...",305 VAPES LLC,305vapesllc@gmail.com,2024-05-21,5
3,2391.0,"BLAZY CONE PINK 1 1/4 21 PACKS PER BOX , BACKW...","LOST MARY 10PK 5% (OS5000) (Pineapple Duo) , B...",3KINGZ LLC,3kingzshop@gmail.com,2024-05-16,5
4,2540.0,GRINDER (GR044-4) 4 PARTS PLASTIC 50MM,Aerospaced By Hs 4 Piece Grinder 63 MM (Gunmet...,BANDARI LLC,bandarillc@gmail.com,2024-02-27,2
...,...,...,...,...,...,...,...
584,54967.0,RAZ 5% 1X5PK DISPOSABLE (9000) (Georgia Peach),HQD PLUS 2.0 5% CINNAMON 1X5PK DISPOSABLE (900...,FRACASSE ENTERPRISES INC,YBOUMECHREK@GMAIL.COM,2024-05-25,5
585,54991.0,.TREE AIRFRESHNER 96CT,HQD V1 5% 3X10PK DISPOSABLE (Strawberry Shortc...,LANTANA GAS STATION INC,usf874@gmail.com,2024-05-30,5
586,55075.0,"305'S 100S FULL FLAVOR , HQD MARS 5% 1X5PK DIS...","VIPER 5PK SUPER 5% (Strawberry Kiwi) , TORCH O...",AFROJA & TAHMIDA FOOD CORP,tahmidabusiness@gmail.com,2024-06-21,6
587,55221.0,".LOTY COCONUT WATER 24-500ML , CAKE 3G D10 5PK...",CAKE 3G D10 5PK DISPOSABLE (STRAWBERRY JAM OG)...,SILVER PETROL LLC,tishad1990@hotmail.com,2024-06-23,6
588,55222.0,ADVIL 24 COATED CAPLETS,"FUME 5PK RESERVE RAINBOW GLUE , MARLEY NATURAL...",MIRAMAR PETRO LLC,tishad1990@hotmail.com,2024-06-15,6

In [3]:
col_drop=['product','Recommended_products','date','last_purchased_month']

df1.drop(col_drop,axis=1,inplace=True)

In [4]:
df1.head()

   customer_id   customer_name             customer_email
0         11.0  Angelo Difatta   angelo@nepawholesale.com
1         14.0  Nepa Wholesale  nepawholesale@hotmail.com
2         46.0   305 VAPES LLC      305vapesllc@gmail.com
3       2391.0      3KINGZ LLC       3kingzshop@gmail.com
4       2540.0     BANDARI LLC       bandarillc@gmail.com

In [5]:
df2=pd.read_csv('final_emails.csv')

In [6]:
df2.head()

                                              Emails
0  Subject: Enhance Your Product Offerings with N...
1  Subject: Enhance Your Offerings with Our Tailo...
2  Subject: Enhance Your Product Offerings with O...
3  Subject: Enhance Your Product Offerings with O...
4  Dear BANDARI LLC,\n\nI hope this email finds y...

In [7]:
df1['Emails']=df2['Emails']

In [8]:
df1.head()

,customer_id,customer_name,customer_email,Emails
0,11.0,Angelo Difatta,angelo@nepawholesale.com,Subject: Enhance Your Product Offerings with N...
1,14.0,Nepa Wholesale,nepawholesale@hotmail.com,Subject: Enhance Your Offerings with Our Tailo...
2,46.0,305 VAPES LLC,305vapesllc@gmail.com,Subject: Enhance Your Product Offerings with O...
3,2391.0,3KINGZ LLC,3kingzshop@gmail.com,Subject: Enhance Your Product Offerings with O...
4,2540.0,BANDARI LLC,bandarillc@gmail.com,"Dear BANDARI LLC,\n\nI hope this email finds y..."

In [9]:
print(df1['Emails'][0])

Subject: Enhance Your Product Offerings with NEPA WHOLESALE's Expert Recommendations

Dear Angelo Difatta,

We hope this email finds you in good spirits. We're delighted to have you as a valued customer at NEPA WHOLESALE.

We've noticed your recent purchases from us on February 19, 2024, including:

â€¢ HQD AIR 5% 1X5PK DISPOSABLE (4000) (Frozen Chocolate)
...etc

To help you expand your offerings and cater to your customers' evolving preferences, we've handpicked a selection of products that we believe will complement your current inventory:

â€¢ FUME NICKY JAM 10PK (10000) (Summer Amante)
â€¢ LOST MARY 5PK 5% (MO5000) (Ginger Bear)
â€¢ SQUID 5K 5% 1X5PK DISPOSABLE (Blue Razz)
â€¢ HQD AIR 5% 1X5PK DISPOSABLE (4000) (Cotton Candy)
â€¢ FUME 10PK MINI 5% DISPOSABLE (600) (Tropical Fruit)
â€¢ DUMMY VAPE 1% DUMMY DREAM 5 PK DISPOSABLE (8K)

â€¢ HQD MAYA 5% 1X5PK DISPOSABLE (6000) (Strawberry Custard)
â€¢ DEATH ROW 5000 5% 5PK DISPOSEABLE (Candy)
â€¢ FUME 10PK RECHARGE 5% DISPOSABLE (5000) (Lemon Mint)
â€¢ LOST MARY 10PK 5% (OS5000) (Pineapple Duo)

These recommendations have been carefully curated to align with your business needs and the latest market trends. Our goal is to empower you with the products that will elevate your offerings and drive customer satisfaction.

If you have any questions or require further assistance, please don't hesitate to contact us. We're committed to supporting your business growth and providing you with the best possible solutions.

Thank you for your continued partnership with NEPA WHOLESALE. We look forward to helping you achieve even greater success.

Best regards,

NEPA WHOLESALE LLC

### Remove Subject

In [10]:
import re



def remove_subject(email):
    if isinstance(email, str):
        return re.sub(r"^Subject:.*\n\n", "", email, flags=re.MULTILINE)
    return email

In [11]:
df1['emails'] = df1['Emails'].apply(remove_subject)

In [12]:
df1['emails']

0      Dear Angelo Difatta,\n\nWe hope this email fin...
1      Dear Nepa Wholesale,\n\nWe hope this email fin...
2      Dear 305 VAPES LLC,\n\nWe hope this email find...
3      Dear 3KINGZ LLC,\n\nWe're thrilled to have you...
4      Dear BANDARI LLC,\n\nI hope this email finds y...
                             ...
584    Dear FRACASSE ENTERPRISES INC,\n\nWe hope this...
585    Dear LANTANA GAS STATION INC,\n\nWe hope this ...
586    Dear AFROJA & TAHMIDA FOOD CORP,\n\nWe're deli...
587    Dear SILVER PETROL LLC,\n\nWe're thrilled to h...
588    Dear MIRAMAR PETRO LLC,\n\nI hope this email f...
Name: emails, Length: 589, dtype: object

In [13]:
df1.sample(10)

,customer_id,customer_name,customer_email,Emails,emails
539,54143.0,786 TASIN LLC,rana954@gmail.com,"Dear 786 TASIN LLC,\n\nWe hope this email find...","Dear 786 TASIN LLC,\n\nWe hope this email find..."
48,22087.0,A AND A GROCERIES INC,ibaida2001@gmail.com,"Dear A AND A GROCERIES INC,\n\nWe're delighted...","Dear A AND A GROCERIES INC,\n\nWe're delighted..."
311,22902.0,MS BARBARA RUSSELL,dj1swagga@gmail.com,"Dear Ms. Russell,\n\nWe hope you're doing well...","Dear Ms. Russell,\n\nWe hope you're doing well..."
197,22577.0,MILK AND THINGS INC,jahid2515@gmail.com,**Paraphrased Email:**\n\nHi MILK AND THINGS I...,**Paraphrased Email:**\n\nHi MILK AND THINGS I...
204,22604.0,INVERSIONES LINRIVE CORP,rivieramobil@powerpetroinc.com,Subject: Enhance Your Product Offerings with O...,"Dear INVERSIONES LINRIVE CORP,\n\nWe hope this..."
213,22624.0,SHARAYN CORPORATION,sharaynco@gmail.com,"Dear SHARAYN CORPORATION,\n\nWe're thrilled to...","Dear SHARAYN CORPORATION,\n\nWe're thrilled to..."
144,22402.0,HEMP STATION,g.topcat@aol.com,Subject: Enhance Your Offerings with Our Tailo...,"Dear HEMP STATION,\n\nWe hope this email finds..."
0,11.0,Angelo Difatta,angelo@nepawholesale.com,Subject: Enhance Your Product Offerings with N...,"Dear Angelo Difatta,\n\nWe hope this email fin..."
239,22688.0,TRINITY PETRO I LLC,jocelynephp@aol.com,Subject: Enhance Your Offerings with Our Tailo...,"Dear TRINITY PETRO I LLC,\n\nWe hope this emai..."
301,22868.0,NAWAZ BROTHERS CORPORATION,snchowdhury@hotmail.com,"Dear NAWAZ BROTHERS CORPORATION,\n\nI hope you...","Dear NAWAZ BROTHERS CORPORATION,\n\nI hope you..."

In [14]:
for i in df1.loc[df1['customer_id']==23427.0,'emails']:
    print(i)

**Paraphrased Email:**

Hi TRIPLE B'S FUEL STATION,

I hope you're doing great! We're so grateful for your ongoing support as a valued customer of NEPA WHOLESALE.

We've noticed your recent purchases from us on April 4, 2024, including:

â€¢ LIGHTENING TO AUXILIARY CABLE 1 CT
â€¢ BACKWOODS 5 PK 40 (Sweet Aromatic)
â€¢ ADVIL LIQUIGEL DISPENSER 25 X 2'S
...etc

To help you expand your offerings and meet customer demand, we've handpicked a few products that we think would be a great fit for your business:

â€¢ BIC PRINTED 50CT POSITIVE AFFIRMATIONS
â€¢ FUME 10PK RECHARGE 5% DISPOSABLE (5000) (Pina-Guava)
â€¢ HOOKAH MIST LUX SPIDER 1CT
â€¢ FUME 10PK RECHARGE 5% DISPOSABLE (5000) (Lemon Mint)
â€¢ SQUID 5K 5% 1X5PK DISPOSABLE (Apple)
â€¢ LOST MARY 10PK 5% (OS5000) (Pineapple Duo)
â€¢ BLINK 9CT UNIX TORCH LIGHTER
â€¢ DUMMY XFINITY 5% 1X5PK DISPOSABLE (6900) (69 Black Ice)
â€¢ SPECIAL BLUE TORCH 1CT (FURY SILVER BUTANE)
â€¢ MARLEY NATURAL STEAMROLLER (Wood & Glass)

We're committed to helping you succeed and provide your customers with the best possible products. These recommendations are tailored to your business needs and the latest market trends.

If you have any questions or need anything else, please don't hesitate to ask. We're here to support you every step of the way.

Thanks again for choosing NEPA WHOLESALE. We value our partnership and look forward to continuing to grow together.

Best,

NEPA WHOLESALE LLC

### remove **parapharse**

In [15]:
def remove_paraphrased(email):
    if isinstance(email, str):
        email = re.sub(r'\*\*Paraphrased Email:\*\*\n\n', '', email)
    return email

In [16]:
df1['emails'] = df1['emails'].apply(remove_paraphrased)

In [17]:
df1.sample(10)

,customer_id,customer_name,customer_email,Emails,emails
182,22529.0,OUR FIVE KIDS LLC,ourfivekidsllc@yahoo.com,**Paraphrased Email:**\n\nDear OUR FIVE KIDS L...,"Dear OUR FIVE KIDS LLC,\n\nWe hope you're doin..."
294,22853.0,BIRIYANY INC,rajupalghat@hotmail.com,"Dear BIRIYANY INC,\n\nI hope this email finds ...","Dear BIRIYANY INC,\n\nI hope this email finds ..."
506,51385.0,WINE SMOKE MUNCHIES LLC,amritshahi2512@gmail.com,Subject: Enhance Your Offerings with Our Tailo...,"Dear WINE SMOKE MUNCHIES LLC,\n\nWe hope this ..."
524,54080.0,MR THEEB LLC,mr.smoke1942@gmail.com,"Dear MR THEEB LLC,\n\nI hope you're doing well...","Dear MR THEEB LLC,\n\nI hope you're doing well..."
551,54297.0,QIT POUCHES INC,accounting@qitpouches.com,"Dear QIT POUCHES INC,\n\nWe hope this email fi...","Dear QIT POUCHES INC,\n\nWe hope this email fi..."
269,22774.0,"SHEMESH ENTERPRISES,LLC",adamshemesh12@gmail.com,"Dear SHEMESH ENTERPRISES,LLC,\n\nWe hope you'r...","Dear SHEMESH ENTERPRISES,LLC,\n\nWe hope you'r..."
7,2828.0,HAPPY LIFE DISTRIBUTION CORP,info@happylifedistributioncorp.com,Subject: Enhance Your Product Offerings with N...,"Dear HAPPY LIFE DISTRIBUTION CORP,\n\nWe hope ..."
125,22350.0,HAFSA & HAIDER SERVICES INC,nazeem.haider@gmail.com,"Dear HAFSA & HAIDER SERVICES INC,\n\nI hope yo...","Dear HAFSA & HAIDER SERVICES INC,\n\nI hope yo..."
531,54093.0,BLAZENPUFF AND STUFF OUT LET LLC,eddie@blazenpuff.com,Subject: Enhance Your Product Line with NEPA W...,"Dear BLAZENPUFF AND STUFF OUT LET LLC,\n\nWe h..."
561,54356.0,OCEAN AVE LLC,vapesplusglass@gmail.com,**Paraphrased Email:**\n\nGreetings OCEAN AVE ...,"Greetings OCEAN AVE LLC,\n\nWe're thrilled to ..."

In [18]:
df1.drop("Emails",axis=1,inplace=True)

In [19]:
df1.head()

,customer_id,customer_name,customer_email,emails
0,11.0,Angelo Difatta,angelo@nepawholesale.com,"Dear Angelo Difatta,\n\nWe hope this email fin..."
1,14.0,Nepa Wholesale,nepawholesale@hotmail.com,"Dear Nepa Wholesale,\n\nWe hope this email fin..."
2,46.0,305 VAPES LLC,305vapesllc@gmail.com,"Dear 305 VAPES LLC,\n\nWe hope this email find..."
3,2391.0,3KINGZ LLC,3kingzshop@gmail.com,"Dear 3KINGZ LLC,\n\nWe're thrilled to have you..."
4,2540.0,BANDARI LLC,bandarillc@gmail.com,"Dear BANDARI LLC,\n\nI hope this email finds y..."

In [20]:
df1.isnull().sum()

customer_id       0
customer_name     0
customer_email    0
emails            1
dtype: int64

In [21]:
df1.dropna(inplace=True)

In [22]:
df1.isnull().sum()

customer_id       0
customer_name     0
customer_email    0
emails            0
dtype: int64

In [23]:
df1.duplicated().sum()

0

In [24]:
df1.to_csv('Emails.csv',index=False)